apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80
       env:
       - name: MY_POD_NAME
         valueFrom:
          fieldRef:
            fieldPath: metadata.name
       volumeMounts:
       - mountPath: /usr/share/nginx/html
         name: index
     initContainers:
     - name: install
       image: busybox
       env:
       - name: MY_POD_NAME
         valueFrom:
          fieldRef:
           fieldPath: metadata.name
       command: ["/bin/sh", "-c", "echo $MY_POD_NAME >> /mnt/index.html"]
       volumeMounts:
       - name: index
         mountPath: "/mnt"
     dnsPolicy: Default
     volumes:
     - name: index
       emptyDir: {}
---
apiVersion: v1
kind: Service
metadata: 
    name: nginx-service
    labels:
        app: nginx
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
    - port: 80
      nodePort: 30030